### ISSUE TITLE
Unexpected view type nested under text node

### ISSUE THREAD

**Issue by matheushf** [SiDevesh/React-Native-FAB#10]
Hi, thanks for the component! 
I'm trying to use a custom icon on it, but I'm getting the error `Unexpected view type nested under text node`, my code is the same from your example:

```
<FAB buttonColor="red" iconTextColor="#FFFFFF" 
onClickAction={() => { console.log("FAB pressed") }} 
visible={true} iconTextComponent={<Icon name="add" />} />
```

Using `import { Icon } from 'react-native-elements';`

**Comment by SiDevesh** [comment]
Hi @matheushf , `iconTextComponent` currently only works with text or icon libraries based on it like `react-native-vector-icons` for example.

**Comment by matheushf** [comment]
Oh thanks, it worked! 
I was thinking the `react-native-vector-icons` inside `react-native-elements` would work
