### ISSUE TITLE
Can't use custom icon

### ISSUE THREAD

**Issue by davidmavec** [SiDevesh/React-Native-FAB#12]
When I try to use attribute **iconTextComponent**, and pass in Icon element, I got the following error:
`Invariant Violation: Nesting of <View> within <Text> is not currently supported.`
Is there any solution for using custom icons?

**Comment by TaeJoongYoon** [comment]
+1

**Comment by TaeJoongYoon** [comment]
https://github.com/SiDevesh/React-Native-FAB/pull/13#issue-222908306

I pull request.
