### ISSUE TITLE
props of 'style' Occur warning 

### ISSUE THREAD

**Issue by TaeJoongYoon** [SiDevesh/React-Native-FAB#15]
![image](https://user-images.githubusercontent.com/24986688/47432271-c272a080-d7d8-11e8-85b4-885bcb0bce19.png)

Like this, props of 'style' occur warning.

So, I try to find a solution.

```javascript
export default class FAB extends Component {
  static propTypes = {
    buttonColor: PropTypes.string,
    iconTextColor: PropTypes.string,
    onClickAction: PropTypes.func,
    iconTextComponent: PropTypes.element,
    visible: PropTypes.bool,
    snackOffset: PropTypes.number,
    style: PropTypes.shape,
  };
```

replace

```javascript
export default class FAB extends Component {
  static propTypes = {
    buttonColor: PropTypes.string,
    iconTextColor: PropTypes.string,
    onClickAction: PropTypes.func,
    iconTextComponent: PropTypes.element,
    visible: PropTypes.bool,
    snackOffset: PropTypes.number,
    style: PropTypes.objectOf(PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.number,
  ])),
  };
```

It doesn't occur warning.

**Comment by headuck** [comment]
The warning goes away when propType of `style` is set to `ViewPropTypes.style`, with `ViewPropTypes` imported from `react-native`.

**Comment by rendy14s** [comment]
Same here ?
There is solution ? @TaeJoongYoon

**Comment by TaeJoongYoon** [comment]
I didn't try @headuck 's idea. But My solution doesn't occur warning

**Comment by rendy14s** [comment]
@TaeJoongYoon you just change this ?

`style: PropTypes.objectOf(PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.number,
  ])),`

**Comment by rahulbhankar786** [comment]
@rendy14s you are rignt. but this is a temp solution. 
when it would be permanently resolved ?

**Comment by TaeJoongYoon** [comment]
@rendy14s Yes, I just change it.

@rahulbhankar786 I think, @headuck 's idea is well.

**Comment by headuck** [comment]
Not particularly my idea, just took reference from [src/Touchable.js](https://github.com/SiDevesh/React-Native-FAB/blob/master/src/Touchable.js)

**Comment by TaeJoongYoon** [comment]
I PR https://github.com/SiDevesh/React-Native-FAB/pull/16/

**Comment by hellohaidev** [comment]
@TaeJoongYoon @headuck 
i have same problem,have a solution?

**Comment by ws7one** [comment]
@TaeJoongYoon 's solution does solve the issue.. any status on when will this get fixed?

**Comment by TaeJoongYoon** [comment]
@ws7one I don't know yet...
