### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by TakaKeiji** [SiDevesh/React-Native-FAB#18]
Please keep this warning in consideration for coming updates

![image](https://user-images.githubusercontent.com/6235078/63894949-dfa96a00-c9bb-11e9-925a-24fc5d3364e5.png)

**Comment by SiDevesh** [comment]
Hi @TakaKeiji ,
This should be a simple fix replacing the lifecycle method,
PRs are always welcome and greatly appreciated.

**Comment by SiDevesh** [comment]
the error from this library itself should be gone in the latest update.
The same lifecycle method deprecation warning also appears in my case from react-native's own components like TouchableOpacity etc.
Those will only be gone once react-native updates them.
