### ISSUE TITLE
Type specification of prop `style` is invalid

### ISSUE THREAD

**Issue by Edweis** [SiDevesh/React-Native-FAB#19]
I put the component in my app render and got : 
```
Warning: FAB: type specification of prop `style` is invalid; the type checker function must return `null` or an `Error` but returned a function. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).
```
Do you know how I can turn off the warning or fix the issue ?

Thanks ! 

Using : `"react": "16.8.3",`

**Comment by luisneto98** [comment]
I have the same error

**Comment by SiDevesh** [comment]
The latest publish version contains the fix for this issue, reopen and let me know if the issue is still unresolved.
