### ISSUE TITLE
 fab visible=false, but component in iconTextComponent visible

### ISSUE THREAD

**Issue by tosh17** [SiDevesh/React-Native-FAB#20]
I start my screen with 
```
 state={is_fab_visible : false}
 <FAB
               ...
              visible={this.state.is_fab_visible} 
              iconTextComponent={<ImageSvg image={"ArrowDownIcon"}/>}/>
```
Fab is not visible on start, but i see ImageSvg  on my screen. And if a swich is_fab_visible to on/off, than ImageSvg   is gone

**Comment by SiDevesh** [comment]
Hi, can you post a complete example of the post so that the issue can be identified.
Here if the state id defined in the render function then `this.state` will be different from that.
