### ISSUE TITLE
Button doesn't float as expected

### ISSUE THREAD

**Issue by arronhunt** [SiDevesh/React-Native-FAB#7]
```jsx
render() {
  return (
    <ScrollView>
       <View style={{height: 9000}} />
       <FAB />
    </ScrollView>
  )
}
```
In a scenario like this, the FAB is pushed all the way to the bottom, and out of view. 

Expected result: 
Button should float above content and always anchor to the lower right, even on scroll

**Comment by rooque** [comment]
can you try putting FAB outside of scrollview ?

```jsx
render() {
  return (
<View>
    <ScrollView>
       <View style={{height: 9000}} />
    </ScrollView>
 <FAB />
</View>
  )
}

**Comment by arronhunt** [comment]
@rooque This solved my issue. Thank you!
